name: cache


on:
  workflow_dispatch:

jobs:
  test-cache:
    name: job to test cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/cache@v3
        id: generateCache
        with:
          path: ~/.cache.zip
          key: ${{ runner.os}}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: pip install -r requirements.txt
      - name: confirm cache
        if: steps.generateCache.outputs.cache-hit == 'true'
        run: echo cahce entry found
